from homeassistant.const import Platform

DOMAIN = "ha_commute_stats"

PLATFORMS = [
    Platform.SENSOR,
    Platform.SWITCH,
    Platform.NUMBER,
    Platform.DATETIME,
]

CONF_PEOPLE = "people"
CONF_PERSON_NAME = "person_name"
CONF_PERSON = "person"
CONF_HOME_ZONES = "home_zones"
CONF_WORK_ZONES = "work_zones"
CONF_HOMETOWN_ZONE = "hometown_zone"
CONF_TOTAL_PEOPLE = "total_people"
CONF_INDOOR_SENSOR = "indoor_sensor"
CONF_AREA_LAT_MIN = "area_lat_min"
CONF_AREA_LAT_MAX = "area_lat_max"
CONF_AREA_LON_MIN = "area_lon_min"
CONF_AREA_LON_MAX = "area_lon_max"
CONF_NOTIFY = "notify"
CONF_AMAP_KEY = "amap_key"
CONF_ANNOUNCE = "announce"
CONF_NOTIFY_ARRIVE = "notify_arrive"
CONF_NOTIFY_LEAVE = "notify_leave"
CONF_NOTIFY_STATION_ENTER = "notify_station_enter"
CONF_NOTIFY_STATION_LEAVE = "notify_station_leave"
CONF_STATION_ENTER_ZONES = "station_enter_zones"
CONF_STATION_LEAVE_ZONES = "station_leave_zones"
CONF_ARRIVE_START = "arrive_start"
CONF_ARRIVE_END = "arrive_end"
CONF_LEAVE_START = "leave_start"
CONF_LEAVE_END = "leave_end"
CONF_ADDR_SENSOR = "addr_sensor"
CONF_COMMUTE_SENSOR = "commute_sensor"
CONF_COMMUTE_DISTANCE = "commute_distance"
CONF_COMMUTE_TIME = "commute_time"
CONF_ACTIVITY_SENSOR = "activity_sensor"

CONF_WORK_ENABLED = "work_enabled"
CONF_STANDARD_HOURS = "standard_hours"
CONF_LUNCH_START = "lunch_start"
CONF_LUNCH_END = "lunch_end"
CONF_OVERTIME_START = "overtime_start"
CONF_CLOCK_IN_START = "clock_in_start"
CONF_CLOCK_IN_END = "clock_in_end"
CONF_CLOCK_OUT_START = "clock_out_start"
CONF_CLOCK_OUT_END = "clock_out_end"
CONF_BASE_SALARY = "base_salary"
CONF_OVER_WAGE = "over_hourly_wage"
CONF_HOLIDAY_WAGE = "holiday_hourly_wage"
CONF_HOLIDAY_SENSOR = "holiday_sensor"
CONF_COMP_THRESHOLD = "comp_threshold"
CONF_COMP_DEDUCT = "comp_deduct"
CONF_DAILY_RESET = "daily_reset"
CONF_RESET_HOME_DURATION = "reset_home_duration"
CONF_MONTHLY_RESET_DAY = "monthly_reset_day"
CONF_WORK_NOTIFY = "work_notify"

MODE_DRIVING = "driving"
MODE_BICYCLING = "bicycling"
ACTIVITY_HOME = "home"
ACTIVITY_COMPANY = "company"
ACTIVITY_OUT = "out"
ACTIVITY_AWAY = "away"
ACTIVITY_BIKE = {ACTIVITY_HOME, ACTIVITY_COMPANY, "在家", "公司"}
ACTIVITY_DRIVE = {ACTIVITY_OUT, ACTIVITY_AWAY, "外出", "外地"}
COMMUTE_BIKE_MAX_M = 10000

TRAVEL_BICYCLING = "bicycling"
TRAVEL_DRIVING = "driving"
TRAVEL_DISTANCE_KM = 10

DEFAULT_TOTAL_PEOPLE = 3
DEFAULT_AREA_LAT_MIN = 30.37
DEFAULT_AREA_LAT_MAX = 31.17
DEFAULT_AREA_LON_MIN = 119.23
DEFAULT_AREA_LON_MAX = 120.47
DEFAULT_NOTIFY_ARRIVE = True
DEFAULT_NOTIFY_LEAVE = True
DEFAULT_NOTIFY_STATION_ENTER = True
DEFAULT_NOTIFY_STATION_LEAVE = True
DEFAULT_ARRIVE_START = "09:00:00"
DEFAULT_ARRIVE_END = "18:00:00"
DEFAULT_LEAVE_START = "00:00:00"
DEFAULT_LEAVE_END = "23:59:00"

DEFAULT_STANDARD_HOURS = 8.0
DEFAULT_LUNCH_START = "12:00:00"
DEFAULT_LUNCH_END = "13:00:00"
DEFAULT_OVERTIME_START = "18:00:00"
DEFAULT_CLOCK_IN_START = "07:00:00"
DEFAULT_CLOCK_IN_END = "13:00:00"
DEFAULT_CLOCK_OUT_START = "13:00:00"
DEFAULT_CLOCK_OUT_END = "23:00:00"
DEFAULT_BASE_SALARY = 0.0
DEFAULT_OVER_WAGE = 0.0
DEFAULT_HOLIDAY_WAGE = 0.0
DEFAULT_COMP_THRESHOLD = 1.0
DEFAULT_COMP_DEDUCT = 1.0
DEFAULT_DAILY_RESET = "00:00:00"
DEFAULT_RESET_HOME_DURATION = False
DEFAULT_MONTHLY_RESET_DAY = 1
DEFAULT_WORK_NOTIFY = False
DEFAULT_WORK_ENABLED = False

STATE_HOLIDAY = "holiday"
STATE_REST = "rest"
STATE_OFF = "off_work"
STATE_LUNCH = "lunch"
STATE_OVERTIME = "overtime"
STATE_WORKING = "working"
HOLIDAY_VALUE = "节假日"

STORAGE_VERSION = 1

WORK_RULE_KEYS = (
    CONF_WORK_ZONES,
    CONF_WORK_ENABLED,
    CONF_STANDARD_HOURS,
    CONF_LUNCH_START,
    CONF_LUNCH_END,
    CONF_OVERTIME_START,
    CONF_CLOCK_IN_START,
    CONF_CLOCK_IN_END,
    CONF_CLOCK_OUT_START,
    CONF_CLOCK_OUT_END,
    CONF_BASE_SALARY,
    CONF_OVER_WAGE,
    CONF_HOLIDAY_WAGE,
    CONF_COMP_THRESHOLD,
    CONF_COMP_DEDUCT,
    CONF_DAILY_RESET,
    CONF_MONTHLY_RESET_DAY,
    CONF_WORK_NOTIFY,
)

HOME_RULE_KEYS = (
    CONF_HOME_ZONES,
    CONF_AREA_LAT_MIN,
    CONF_AREA_LAT_MAX,
    CONF_AREA_LON_MIN,
    CONF_AREA_LON_MAX,
    CONF_NOTIFY_ARRIVE,
    CONF_NOTIFY_LEAVE,
    CONF_ARRIVE_START,
    CONF_ARRIVE_END,
    CONF_LEAVE_START,
    CONF_LEAVE_END,
    CONF_NOTIFY_STATION_ENTER,
    CONF_NOTIFY_STATION_LEAVE,
    CONF_STATION_ENTER_ZONES,
    CONF_STATION_LEAVE_ZONES,
    CONF_RESET_HOME_DURATION,
)
